export {default as Home } from './Home'
export {default as HotelDetails} from './HotelDetails'
export {default as Profile} from './Profile'
export {default as ShowHotels} from './ShowHotels'
export {default as Signup} from './Signup'
export {default as Payment} from './Payment'
export {default as Login} from './Login'
export {default as Attractions} from './Attractions'
export {default as Footer} from '../Components/Footer'
export {default as ProtectedRoute} from '../Components/ProtectedRoute'